### ISSUE TITLE
How can i install this on anaconda?

### ISSUE THREAD

**Issue by kritiksoman** [dharhas/smear#2]
I am new to using python. Could you please advise on how i could install this on a system running anaconda.

**Comment by dharhas** [comment]
This is not a mature package. I haven't worked on it in 5 years. If you are new to python it might not be the best fit.

That said, to install it on anaconda, you would have to make sure all its dependencies where installed, i.e. look at setup.py for the list. After that, you would need to install from source. Download or clone the source code, then run 'python setup.py install' from the source directory.
